project:
  type: website


website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hand-on_EX/Hand-on-EX01/Hands-on_EX01.html"
          - text: "Hands-on Exercise 2"
            href: "Hand-on_EX/Hand-on-EX02/Hands-on_EX02.html"
          - text: "Hands-on Exercise 3"
            href: "Hand-on_EX/Hand-on-EX03/Hands-on_EX03.html"
          - text: "Hands-on Exercise 4"
            href: "Hand-on_EX/Hand-on-EX04/Hands-on_EX04.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: "In-class_EX/In-class_EX01/In-class EX01.html"
          - text: "In-class Exercise 2"
            href: "In-class_EX/In-class_EX02/In-class EX02.html"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_EX/Take-home_EX01/Take-home Exercise 1.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_EX/Take-home_EX02/Take-home Exercise_2.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: Superhero
    css: styles.css
    toc: true

editor: visual

